branch-defaults:
  main:
    environment: res-checker-env
    group_suffix: null
environment-defaults:
  reschecker-env:
    branch: null
    repository: null
global:
  application_name: ResChecker2
  branch: null
  default_ec2_keyname: res_checker_key
  default_platform: Python 3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
